version: '3'

services:
  app1:
    build:
      context: .
      args:
        NODE_ID: node-1
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=node-1

  app2:
    build:
      context: .
      args:
        NODE_ID: node-2
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=node-2

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2